{% set name = "torchsurv" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7a7487ea8296ca02744b4e975e70882ce9c70e6bad14649379dd3aa787cbeaf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - pytorch
    - scipy
    - numpy
    - torchmetrics

test:
  imports:
    - torchsurv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://opensource.nibr.com/torchsurv
  summary: Deep survival analysis made easy with pytorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkrusche
    - kruscpe1
    - tcoroller
